name: Github Actions Demo
run-name: ${{github.actor}} is testing out Github Actions
on: [push]
jobs:
  Explore-github-actions
  runs-on: ubuntu-latest
  steps:
    - run: echo "ğŸ‰ The job was automatically triggered by a ${{
    github.event_name}} event."
    - run: echo "ğŸ§ this job is now running on a ${{runner.os}} server 
    hosted by GitHub!"
    - run: echo "ğŸ” the name of your branch is ${{github.ref}} and your
    repository is ${{github.repository}} repository."
    - name: Check out repository code
    uses: actions/checkout@v4
    - run: "ğŸ’¡ The ${{github.repository}} has been cloned to the runner 
    to the runner."
    - run: echo "ğŸ–¥ï¸ the workflow is now ready to test your code on the 
    runner."
    - name: list files in the repository
    - run: | 
        ls ${{github.workspace}} 
    - run: echo "ğŸ This job's status is ${{job.status}}." 
   
